import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20 
ASTEROID_KINDS = 10
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_ACCELERATION = 1.5
ASTEROID_LIFETIME = 2

PLAYER_RADIUS = 20

SCREEN_COLOR = pygame.Color("black")
PLAYER_COLOR = pygame.Color("white")
SHOT_COLOR = pygame.Color("green")

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_BASE_HEALTH = 200

SHOT_RADIUS = 5
PLAYER_SHOOT_COOLDOWN = 0.1
SHOT_LIFETIME = 5
